# permissions for end users to edit lolcows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lolcow-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - lolcows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - lolcows/status
  verbs:
  - get
